// v0.0.57: Saved Filters helpers - rebuilt to match Labels architecture exactly
import type { SavedFilter, FilterQuery } from './schema'
import { db } from './dexieClient'

export const SavedFilters = {
  list: () => db.savedFilters.toArray(),
  get: (id: number) => db.savedFilters.get(id),

  // v0.0.57: Add method - simplified like Labels.add
  add: async (input: { name: string; queryJson: FilterQuery; menuVisible?: boolean; shared?: boolean; ownerId: number }) => {
    const now = new Date().toISOString()
    const filter: SavedFilter = {
      id: 0, // Will be auto-generated by Dexie
      name: input.name,
      normalizedName: input.name.trim().toLowerCase(),
      queryJson: input.queryJson,
      menuVisible: input.menuVisible !== undefined ? input.menuVisible : true,
      shared: input.shared !== undefined ? input.shared : true,
      ownerId: input.ownerId,
      createdAt: now,
      updatedAt: now,
      version: 1,
    }
    const id = await db.savedFilters.add(filter)
    return id
  },

  // v0.0.57: Update method - like Labels.update
  update: async (id: number, patch: Partial<SavedFilter>) => {
    if (!patch.updatedAt) {
      patch.updatedAt = new Date().toISOString()
    }
    // Increment version on update (like Labels)
    const current = await db.savedFilters.get(id)
    if (current) {
      patch.version = current.version + 1
    }
    await db.savedFilters.update(id, patch)
  },

  // v0.0.57: Remove method - like Labels.remove
  remove: (id: number) => db.savedFilters.delete(id),
}
